# Generated by Django 5.2.8 on 2025-12-09 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("openkat", "0001_initial")]

    operations = [migrations.RemoveField(model_name="user", name="onboarded")]
