# Generated by Django 5.2.8 on 2025-12-09 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("openkat", "0002_remove_user_onboarded")]

    operations = [migrations.DeleteModel(name="Indemnification")]
