# Generated by Django 5.2.9 on 2025-12-11 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("openkat", "0003_delete_indemnification")]

    operations = [migrations.RemoveField(model_name="organization", name="code")]
