# Generated by Django 5.2.8 on 2025-11-25 11:52

import django.contrib.postgres.fields
import django.db.models.deletion
import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("openkat", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="BusinessRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"permissions": [("run_businessrule", "Can run a business rule")]},
        ),
        migrations.CreateModel(
            name="Plugin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plugin_id", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "scan_level",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "L0"), (1, "L1"), (2, "L2"), (3, "L3"), (4, "L4")], default=4
                    ),
                ),
                (
                    "consumes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=128), blank=True, default=list, size=None
                    ),
                ),
                ("recurrences", recurrence.fields.RecurrenceField(blank=True, null=True)),
                (
                    "batch_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override the global BATCH_SIZE setting for this plugin. Set to 0 to disable batching.",
                        null=True,
                    ),
                ),
                ("oci_image", models.CharField(max_length=256, null=True)),
                (
                    "oci_arguments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=256), default=list, size=None
                    ),
                ),
                ("version", models.CharField(max_length=16, null=True)),
                ("permissions", models.JSONField(default=dict)),
            ],
            options={"permissions": [("run_plugin", "Can run a plugin")]},
        ),
        migrations.CreateModel(
            name="PluginSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("settings", models.JSONField(default=dict)),
                ("organizations", models.ManyToManyField(related_name="plugin_settings", to="openkat.organization")),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="plugin_settings", to="plugins.plugin"
                    ),
                ),
            ],
        ),
    ]
