# Generated by Django 5.2.8 on 2025-11-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0014_plugin_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugin',
            options={'permissions': [('run_plugin', 'Can run a plugin')]},
        ),
    ]
