# Generated by Django 5.2.8 on 2025-11-24 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("plugins", "0015_alter_plugin_options")]

    operations = [
        migrations.RemoveField(model_name="businessrule", name="finding_type_code"),
        migrations.RemoveField(model_name="businessrule", name="inverse_query"),
        migrations.RemoveField(model_name="businessrule", name="object_type"),
        migrations.RemoveField(model_name="businessrule", name="query"),
        migrations.RemoveField(model_name="businessrule", name="requires"),
    ]
