# Generated by Django 5.2.8 on 2025-11-25 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("openkat", "0001_initial"), ("reports", "0001_initial"), ("tasks", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="report",
            name="object_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="tasks.objectset",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="organizations",
            field=models.ManyToManyField(blank=True, related_name="filtered_reports", to="openkat.organization"),
        ),
    ]
