# Generated by Django 5.2.8 on 2025-11-28 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("tasks", "0001_initial")]

    operations = [
        migrations.RenameField(model_name="objectset", old_name="all_objects", new_name="static_objects"),
        migrations.RemoveField(model_name="schedule", name="operation"),
        migrations.RemoveField(model_name="schedule", name="run_on"),
    ]
