# Generated by Django 5.2.8 on 2025-11-21 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("openkat", "0004_alter_organization_options"), ("tasks", "0009_remove_objectset_subsets")]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="openkat.organization",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="organization",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="openkat.organization"
            ),
        ),
    ]
