# Generated by Django 5.2.8 on 2025-11-18 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("files", "0002_initial")]

    operations = [
        migrations.AlterModelOptions(name="file", options={"permissions": (("download_file", "Can download files"),)})
    ]
