"""add index for boefje_meta org+boefje_id+inputooi in desc order

Revision ID: 2380422e773e
Revises: 1dde0213e9fe
Create Date: 2026-06-29 12:44:37.532792

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2380422e773e"
down_revision = "1dde0213e9fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raw_file_boefje_meta_id"), table_name="raw_file")
    op.drop_index(op.f("ix_raw_file_signing_provider_id"), table_name="raw_file")
    op.drop_table("raw_file")
    op.drop_index(op.f("ix_boefje_meta_organization_boefje_id"), table_name="boefje_meta")
    op.drop_table("boefje_meta")
    op.drop_index(op.f("ix_normalizer_meta_raw_file_id"), table_name="normalizer_meta")
    op.drop_table("normalizer_meta")
    op.drop_table("signing_provider")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signing_provider",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('signing_provider_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("url", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="signing_provider_pkey"),
        sa.UniqueConstraint("url", name="signing_provider_url_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "normalizer_meta",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("normalizer_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("normalizer_version", sa.VARCHAR(length=16), autoincrement=False, nullable=True),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("ended_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("raw_file_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_file_id"], ["raw_file.id"], name=op.f("normalizer_meta_raw_file_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("normalizer_meta_pkey")),
    )
    op.create_index(op.f("ix_normalizer_meta_raw_file_id"), "normalizer_meta", ["raw_file_id"], unique=False)
    op.create_table(
        "boefje_meta",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("boefje_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("boefje_version", sa.VARCHAR(length=16), autoincrement=False, nullable=True),
        sa.Column("organization", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("arguments", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("ended_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("input_ooi", sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
        sa.Column("environment", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("runnable_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="boefje_meta_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_boefje_meta_organization_boefje_id"), "boefje_meta", ["organization", "boefje_id"], unique=False
    )
    op.create_table(
        "raw_file",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("secure_hash", sa.VARCHAR(length=256), autoincrement=False, nullable=True),
        sa.Column("hash_retrieval_link", sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
        sa.Column("boefje_meta_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("mime_types", postgresql.ARRAY(sa.VARCHAR(length=64)), autoincrement=False, nullable=True),
        sa.Column("signing_provider_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["boefje_meta_id"], ["boefje_meta.id"], name=op.f("raw_file_boefje_meta_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["signing_provider_id"],
            ["signing_provider.id"],
            name=op.f("raw_file_signing_provider_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("raw_file_pkey")),
    )
    op.create_index(op.f("ix_raw_file_signing_provider_id"), "raw_file", ["signing_provider_id"], unique=False)
    op.create_index(op.f("ix_raw_file_boefje_meta_id"), "raw_file", ["boefje_meta_id"], unique=False)
    # ### end Alembic commands ###
